### ISSUE TITLE
Rust的内存安全具体指的是什么

### ISSUE THREAD

**Issue by Gnosnay** [rust-zh/faq#1]
The book上说rust解决不了内存泄露

> Rust’s memory safety guarantees make it difficult, but not impossible, to accidentally create memory that is never cleaned up (known as a memory leak). Preventing memory leaks entirely is not one of Rust’s guarantees in the same way that disallowing data races at compile time is, meaning memory leaks are memory safe in Rust.

那么rust所提供的内存安全保证含义究竟是什么呢

**Comment by upsuper** [comment]
感谢你的问题。

这个FAQ主要是收录在[Rust众](https://t.me/rust_zh)的群里多次讨论，并且对于答案有一定共识的问题，不是作为提出和回答问题的地方。这个问题我印象中没怎么在群里见过，如果有不明白可以先在群里讨论。
